// Objective-C API for talking to github.com/vr33ni/eisbachtracker-pwa/go-server/tempservice Go package.
//   gobind -lang=objc github.com/vr33ni/eisbachtracker-pwa/go-server/tempservice
//
// File is generated by gobind. Do not edit.

#ifndef __Tempservice_H__
#define __Tempservice_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT BOOL TempserviceGetLatestTemperature(double* _Nullable ret0_, NSError* _Nullable* _Nullable error);

#endif
