
// Objective-C API for talking to the following Go packages
//
//	github.com/vr33ni/eisbachtracker-pwa/go-server/tempservice
//
// File is generated by gomobile bind. Do not edit.
#ifndef __TempService_FRAMEWORK_H__
#define __TempService_FRAMEWORK_H__

#include "Tempservice.objc.h"
#include "Universe.objc.h"

#endif
